// LLM response module for the Google Agent Development Kit (ADK) in TypeScript
// Mirrors the LLM response functionality from the Python SDK

import { Content } from './llm_types';

/**
 * Response from a language model.
 */
export class LlmResponse {
  /**
   * The content generated by the model.
   */
  content?: Content;

  /**
   * Error code if there was an error.
   */
  errorCode?: string;

  /**
   * Error message if there was an error.
   */
  errorMessage?: string;

  /**
   * Whether the response was interrupted.
   */
  interrupted?: boolean;

  /**
   * Whether the response is partial.
   */
  partial?: boolean;

  /**
   * Whether the turn is complete.
   */
  turnComplete?: boolean;

  /**
   * Actions to take based on the response.
   */
  actions?: Record<string, any>;

  /**
   * Creates a new LlmResponse.
   */
  constructor(data: {
    content?: Content;
    errorCode?: string;
    errorMessage?: string;
    interrupted?: boolean;
    partial?: boolean;
    turnComplete?: boolean;
    actions?: Record<string, any>;
  } = {}) {
    this.content = data.content;
    this.errorCode = data.errorCode;
    this.errorMessage = data.errorMessage;
    this.interrupted = data.interrupted;
    this.partial = data.partial;
    this.turnComplete = data.turnComplete;
    this.actions = data.actions;
  }
}